- bot.ml
It's not magic so it still fails on conflicts.
I don't know how to test so didn't.
> Automatically merge before pushing instead of is-ancestor check

- README.md
- bot.ml
This PR removes deprecated password/login authentication in favor of authentication tokens, fixing #46.
> Authenticate with access token.

- README.md
> Update instructions for GitLab

- README.md
- bot-components/GitHub_GraphQL.ml
- bot-components/GitHub_mutations.ml
- bot-components/GitHub_queries.ml
- bot.ml
Since the extra queries yield timeouts from the server.
> Undo GraphQL conversions

- CHANGELOG.md
Summary of the features of coqbot 0.1.0.
> Changelog of coqbot 0.1.0.

- bot-components/GitHub_GraphQL.ml
- bot-components/GitHub_queries.ml
- bot-components/GitHub_subscriptions.ml
- bot.ml
> Print commit hash and message in allow_failure notification.

- bot-components/GitHub_mutations.ml
- bot-components/GitHub_queries.ml
- bot-components/GitHub_subscriptions.ml
- bot-components/GitLab_mutations.ml
- bot-components/GitLab_queries.ml
- bot-components/Utils.ml
- bot.ml
Coqbot can now respond to minimization requests in the body of an issue.
We also ignore commented @coqbot messages (preceded by `<!--`), allow to invoke the minimizer without a colon after @coqbot and replace every occurrence of `coqbot` with the global variable `bot_name`.
> Run bug minimizer on new issues

- bot-components/GitHub_GraphQL.ml
- bot-components/GitHub_queries.ml
- bot-components/GitHub_subscriptions.ml
- bot.ml
Disable merge by email to guaranty the authenticity of the message.
> Disable merge by email

- bot-components/GitHub_subscriptions.ml
- bot.ml
Fixes a regression introduced in #81
> Don't check if review comments are created by email.

- bot-components/GitHub_mutations.ml
- bot-components/GitHub_queries.ml
- bot-components/GitHub_subscriptions.ml
- bot-components/GitHub_types.mli
- bot-components/GitLab_subscriptions.ml
- make_ancestor.sh
- src/actions.ml
- src/git_utils.ml
- src/git_utils.mli
> Use a more descriptive title in merge commits

- bot-components/GitLab_subscriptions.ml
- make_ancestor.sh
See commit content for details.
> Fix lack of merge commit when the PR is up to date with master

- bot-components/GitHub_app.ml
> Fix error handling.

- src/git_utils.ml
Fix https://github.com/coq/bot/issues/98
> quote pr title properly

- bot-components/Bot_info.ml
- bot-components/GitHub_GraphQL.ml
- bot-components/GitHub_mutations.ml
- bot-components/GitHub_mutations.mli
- bot-components/GitHub_queries.ml
- bot-components/GitHub_queries.mli
- bot-components/GitHub_subscriptions.ml
- bot-components/GitHub_subscriptions.mli
- bot-components/GitHub_types.mli
- bot-components/GraphQL_query.ml
- bot-components/GraphQL_query.mli
- bot-components/Utils.ml
- bot-components/Utils.mli
- bot-components/dune
- bot-components/schema.json
- src/actions.ml
- src/actions.mli
- src/bot.ml
- src/git_utils.ml
- src/git_utils.mli
- src/github_installations.ml
- src/helpers.ml
- src/helpers.mli
Preliminary support for the GitHub Checks API.
> Checks API

- src/actions.ml
Send status checks for Coq HTML documentation builds.
> Send status checks for refman and stdlib.

- CHANGELOG.md
- README.md
- coqbot-config.toml
- example-config.toml
- src/config.ml
This PR aims to improve the Readme and publish some release notes.
> Documentation

- bot-components/GitHub_GraphQL.ml
- bot-components/GitHub_mutations.ml
- bot-components/GitHub_mutations.mli
- src/actions.ml
- src/git_utils.ml
We should do the same thing for other mutations.
> Log when posting comment.

- bot-components/GitHub_GraphQL.ml
- bot-components/GitHub_queries.ml
- bot-components/GitHub_queries.mli
- bot-components/GitHub_types.mli
- bot-components/GitLab_subscriptions.ml
- bot-components/GitLab_types.mli
- coq_bug_minimizer.sh
- release.Dockerfile
- run_ci_minimization.sh
- src/actions.ml
- src/actions.mli
- src/bot.ml
- src/git_utils.ml
- src/git_utils.mli
When a PR pipeline completes, looks for the library builds that failed in the PR but did not fail for the base commit.
For now, nothing is done besides adding to the log.
When this is finished, this will resolve #107.
> Minimize failed tests.

- src/bot.ml
- src/git_utils.ml
> Fix quoting and regex parsing for minimization

- src/bot.ml
Fix a parsing bug I introduced in https://github.com/coq/bot/pull/144/files#r648423852
I wonder if we should do less shadowing...
> Fix a parsing bug I introduced in https://github.com/coq/bot/pull/144/files#r648423852

- src/actions.ml
See https://github.com/coq/coq/pull/13072#issuecomment-857781670 for
incorrect rendering
> Separate lists from subsequent paragraphs

- run_ci_minimization.sh
- src/actions.ml
- src/actions.mli
- src/bot.ml
- src/git_utils.ml
- src/git_utils.mli
> Enable CI minimization resumption

- src/actions.ml
> Fix trimming of CI job names for correct comparison

- bot-components.opam
- bot-components/GitHub_GraphQL.ml
- bot-components/GitHub_mutations.ml
- bot-components/GitHub_queries.ml
- bot-components/GitHub_types.mli
- bot-components/GraphQL_query.ml
- bot-components/GraphQL_query.mli
- bot-components/dune
- coq-bot.opam
- dune-project
- src/config.ml
- src/config.mli
> Adapt to toml 6.0.0

- bot-components.opam
- bot-components/GitHub_GraphQL.ml
- bot-components/GitHub_mutations.ml
- bot-components/GitHub_queries.ml
- bot-components/GitHub_types.mli
- bot-components/GraphQL_query.ml
- bot-components/GraphQL_query.mli
- bot-components/dune
- dune-project
This branch is a WIP to update to graphql-ppx 1.2.0.
Due to the large changes in the way that graphql-ppx work, important refactorings of the `bot-components` library could be done, but this is just an (WIP) attempt at upgrading to start with.
> Update graphql-ppx to 1.2.0

- bot-components/dune
Since read will read the newline and some editors add a newline at the end of files
> read-strings is preferred to read 

- src/actions.ml
When the bench job starts and and finishes we push the check status for it. I am not sure how to do it for a failure, so perhaps I should forgo the status checking all together?
> Add bench to check status

- bot-components/GitHub_GraphQL.ml
- bot-components/GitHub_mutations.ml
- bot-components/GitHub_mutations.mli
- bot-components/GitHub_queries.ml
- bot-components/GitHub_queries.mli
- src/actions.ml
Depends on #214
Here it is in actions: https://github.com/coq/coq/pull/14748/checks?check_run_id=5651821583
> Bench report

- bot-components/GitHub_GraphQL.ml
- bot-components/GitHub_queries.ml
- bot-components/GitHub_queries.mli
Hopefully, this should be just what @Alizter needs to get the bot to post a comment summarizing a bench run.
> Add `get_pull_request_id` query.

- src/actions.ml
Fix https://github.com/coq/bot/issues/237.
> When suggesting minimization, use base and head sha from webhook.

- bot-components/GitLab_mutations.ml
I didn't push my latest changes whoops.
> Fixup to bench native

- bot-components/GitHub_mutations.ml
- bot-components/GitHub_queries.ml
- bot-components/GitLab_GraphQL.ml
- bot-components/GitLab_queries.ml
- bot-components/GitLab_queries.mli
- bot-components/GraphQL_query.ml
- bot-components/GraphQL_query.mli
- bot-components/dune
- src/actions.ml
- src/bot.ml
This will avoid retrying many times a job when the runner keeps failing.
Fixes #239.
> Support for GitLab GraphQL queries. Use to check nb of retries.

- coq_bug_minimizer.sh
> Make commit messages more informative in minimization

- coq_bug_minimizer.sh
> Slightly nicer commit message for minimizer

- src/actions.ml
cf https://github.com/coq/coq/pull/16857
> Print failing bench jobs

- src/bot.ml
This will allow more local editing of the parsing code in #262, and should make review easier.
> Collect parsing of ci minimization in one place

- src/helpers.ml
- src/helpers.mli
Splitting this out from #262 for ease of review; please suggest more maintainable / idomatic ways of implementing these functions if there are such
> Add some string matching utils

- coq_bug_minimizer.sh
- run_ci_minimization.sh
- src/actions.ml
- src/actions.mli
- src/bot.ml
- src/git_utils.ml
- src/git_utils.mli
Also for `@coqbot extra-arg=--inline-coqlib resume ci minimize ci-foo` and `@coqbot extra-arg=--inline-coqlib ci minimize ci-foo`
On top of #257 to avoid conflicts
For https://github.com/coq/coq/pull/16967#issuecomment-1372540099, in conjunction with https://github.com/JasonGross/coq-tools/pull/144
> Add support for `@coqbot inline-stdlib=yes resume ci minimize ci-foo`

- src/actions.ml
As per https://github.com/github/linguist/blob/c1c34e5260797b4d598f5ec76f19723bfc5a1894/lib/linguist/languages.yml#L6207-L6211
Fixes #268
> Handle more kinds of code blocks in the minimizer

- src/actions.ml
Since this has no change in behavior other than debugging, I'm going to merge shortly
> Add more debugging info about parsing script quotes

- src/actions.ml
Inform unauthorized users when they try to run coqbot commands + refactor common code.
I'll test-deploy.
> Inform unauthorized users when they try to run coqbot commands.

- bot-components/GitHub_queries.ml
and reorder code so that short error branches go before the main branch
> Fix "got more than one checkSuite" message when actually got 0

- src/actions.ml
Related: https://github.com/coq/bot/issues/289#issuecomment-2226848078
Example-log: https://gitlab.inria.fr/math-comp/docker-mathcomp/-/jobs/4509247
Cc @Zimmi48 @palmskog
> Rebuild if error "received unexpected HTTP status: 502 Bad Gateway" is raised

- src/actions.ml
Spotted in this gitlab.inria.fr job today:
https://gitlab.inria.fr/math-comp/math-comp/-/jobs/4607507
Cc @Zimmi48:
Does the patch looks good to you?
> Extend connectivity check

- src/actions.ml
> bug-minimizer: link to run-coq-bug-minimizer/actions more

- .github/CONTRIBUTING.md
- bot-components/GitHub_GraphQL.ml
- bot-components/GitHub_queries.ml
- bot-components/GitLab_GraphQL.ml
- bot-components/GraphQL_query.ml
- src/actions.ml
- src/git_utils.ml
Alternative to #315 
Closes #315
> `dune build @fmt --auto-promote` with ocamlformat 0.26.2 

- bot-components/GitHub_GraphQL.ml
- bot-components/GitHub_queries.ml
- bot-components/GitHub_queries.mli
- src/actions.ml
Closes #343.
I'm going to test-deploy this. @proux01 can you craft a PR with `offer-minimizer: off` in the body and a code change that would normally make the minimizer offer suggestions to test that it works?
EDIT: to check the deployment status: https://github.com/Zimmi48/bot/actions/runs/16068760889
> Include option to disable minimization suggestions in PR body.

- src/actions.ml
To be merged only after the pull request template has been modified for a few months.
> Invert the logic of the auto-minimization suggestions.

- src/actions.ml
> Report more detailed information when failing to find pipeline checks
