rocq-prover/bot

bot.ml
make_ancestor.sh

This should ensure fresh state better.
I split the merge command to a new sh file as doing concatenations in
ocaml is a pain and stops me from using shell linters etc.
This probably doesn't work as the call to make_ancestor.sh is using
PATH and I don't think it's in PATH, how to fix?

Do merge in fresh worktree

---

README.md

Some menus to use the @coqbot instance in a repository have changed.

Update coqbot usage instructions

---

bot.ml

This fixes #55 by extracting the project name from the repository url first, and falling back to the `project_name` key if it fails.

Fix project name for job actions.

---

bot-components/GitHub_GraphQL.ml
bot-components/GitHub_queries.ml
bot-components/GitHub_subscriptions.ml
bot.ml

This is what was requested at the Coq Call today: if a job fails in allow failure mode, the bot checks if it was on a PR branch (`pr-<num>`) and if the commit corresponds to the current head of the branch. If that's the case, it posts a comment informing of the failure. In the special case where the failure was for the `library:ci-fiat_crypto_legacy`, then it pings @JasonGross.
The first commit is only a preliminary refactoring, the second commit is the one that adds the feature.

Post a comment when a job in allow failure mode fails.

---

README.md
bot-components/GitHub_GraphQL.ml
bot-components/GitHub_mutations.ml
bot-components/GitHub_queries.ml
bot-components/GitLab_mutations.ml
bot-components/GitLab_queries.ml
bot-components/Utils.ml
bot.ml

After moving the GitHub/GitLab queries and mutations to the relevant modules, we then rewrite `add_rebase_label` to use GitHub's GraphQL API.

Moving the GitHub/GitLab queries and mutations to the relevant modules

---

bot-components/dune

There was a missing `(mode promote)` to a rule in the dune file which caused an error during compilation, as reported in issue #58.

Add (mode promote) to rule in dune file.

---

Dockerfile
bot-components/GitHub_subscriptions.ml
bot.ml
coq_bug_minimizer.sh

This patch allows coqbot to reply to '@coqbot: minimize' messages with the results of @JasonGross' [Coq bug minimizer](https://github.com/JasonGross/run-coq-bug-minimizer).
Here is an example:
Before merging this, we'd need to change the repository in the `coq_bug_minimizer` script to the original one (it uses a fork currently).
I also did some preliminary work to listen to check run events, so that coqbot could reply back once the check run starts, with a link to the running check.

Integrate with run-coq-bug-minimizer GitHub action.

---

bot.ml

The first time I've used the bot merge feature (coq/coq#12767), I've forgotten the `:`.

Be more tolerant to how the messages to coqbot are written.

---

bot-components/GitHub_subscriptions.ml
coq-bot.opam
default.nix
dune-project

Let's compare cryptographic hashes in constant time to prevent timing attacks from happening.
These changes depend on #83

Constant time equality

---

README.md

Initially, the App was only installed for the Coq repository in the Coq organization, but this resulted in status checks for the opam-coq-archive repository to be rejected.

Document a limitation regarding the install method.

---

src/actions.ml

Close #139
However this isn't enough to get github to display the assignee's
icon, we need to add the email for that.

Add Co-authored-by: merger to coqbot merges

---

src/bot.ml

According to https://ocaml.org/api/Str.html, `.` "[m]atches any
character except newline."  It was previously only catching the first line.  Oops.

Fix coqbot minimize regex

---

src/actions.ml

Partial revert of 074d402, because the body of coqbot minimize stamps does not include the PR number
Lmk if I should drop the ocamlformat reformatting commit (but 0.15.0 is incompatible with graphql_ppx>=1.2 on OCaml >=4.11, so maybe we should bump the ocamlformat version?)

Fix coqbot minimize (without CI)

---

bot-components/GitHub_app.ml

from one hour to 55 minutes to make sure that it's not above one hour (max allowed by GitHub)
Fixes #204

Changing expiration date 

---

bot-components/GitHub_app.ml
bot-components/GitHub_mutations.ml
bot-components/GitHub_subscriptions.ml
src/actions.ml
src/git_utils.ml

This is a QoL change because I find it hard to read and debug strings that have `\"` instead of simply `"`

Strings that need to use double quotes are now enclosed in {| |} for readability

---

bot-components/GitHub_mutations.ml
bot-components/GitHub_mutations.mli
src/actions.ml

I'm trying this on a newer version of OCaml (4.12.1) and there is a warning about optional arguments that cannot be erased. Having a look at GitHub_mutations.merge_pull_requests there is no way for OCaml to understand a partial application. In order to fix this we just need to add a thunk.

thunk merge_pull_request since optional args cannot be deleted otherwise

---

bot-components/GitHub_GraphQL.ml
bot-components/GitHub_queries.ml
bot-components/GitHub_queries.mli
bot-components/GitLab_mutations.ml
bot-components/GitLab_mutations.mli
src/actions.ml
src/actions.mli
src/bot.ml

We can now tell coqbot to start the bench in a PR with `@coqbot bench`.
I haven't tested the regex fully so we need to try it out before deploying fully like usual.

Add bench command for coqbot

---

bot-components/GitLab_mutations.ml
bot-components/GitLab_mutations.mli
src/actions.ml
src/actions.mli
src/bot.ml

We should now be able to do `@coqbot bench native`. Once https://github.com/coq/coq/pull/16679 lands.
This defo needs testing since the GitLab docs on the env var for the job are so poor.

Add functionality to bench native

---

src/bot.ml
src/config.ml
src/config.mli

This makes it only be called when needed. Otherwise it gets called during linking and that affects unreleated things.

thunk Config.github_private_key

---

coq-bot.opam
default.nix
dune-project
src/bot.ml
src/config.ml
src/dune

This lets us write inline expectation tests which is quite useful especially in a hard to test application like coqbot.
Depends on #244.

Add ppx_expect as a dependency

---

coq_bug_minimizer.sh
src/actions.ml
src/actions.mli
src/bot.ml
src/git_utils.ml
src/git_utils.mli

Not entirely clear what the protocol should be, see also #183.  We
currently allow things like `coq-8.14` and `coq.dev` and `coq: dev` and
`ocaml: 4.11`, etc.

Allow customization of Coq version

---

src/actions.ml
src/actions.mli
src/bot.ml

We now assume that `@coqbot minimize` is followed by a Coq file, not a bash script, unless the user begins with ` ```sh` or ` ```bash` or the script begins with `#!`.
Additionally, we also allow the user to say `@coqbot minimize [text](url)`, and use the `handle-web-file.sh` script in the run-coq-bug-minimizer to automatically download `url` and automagically figure out how to build run coq on it.  (Currently there's support for uncompressing archives, running single .v files, renaming text files to .v if there's no archive, finding _CoqProject, and using autogen, configure, and make to build archives if there's a single makefile.)
Fixes #256

Improve minimization logic around scripts and files

---

src/bot.ml

This should fix the issue where ` ```bash ` is not recognized because there's apparently a trailing space or `\r`.

Strip spaces from quote_kind

---

src/actions.ml

Fixes #290.
The first commit adapts the job trace parsing after coq/coq#17785, but it seems like it is not enough because the way to retrieve the image the job ran on has changed after moving to Inria GitLab.

Adapt the job trace parsing for Checks tab summary after recent changes.

---

src/actions.ml

This should issues like
https://github.com/coq/coq/pull/18446/checks?check_run_id=20043646334 not finding `Error` since the introduction of colors in https://github.com/coq/coq/pull/18338.  ANSI color codes sometimes include three numeric components.  If we want to be more precise, we could use `([0-9]+;?){1,3}` or even `([0-9]+;){0,2}[0-9]+`, but I think this might be overkill, and there's not too much harm in using the simpler expression.

Strip out more ANSI color codes

---

bot-components/GitHub_GraphQL.ml
bot-components/GitHub_app.ml
bot-components/GitHub_app.mli
bot-components/GitHub_mutations.ml
bot-components/GitHub_mutations.mli
bot-components/GitHub_queries.ml
bot-components/GitHub_queries.mli
bot-components/GitHub_subscriptions.ml
bot-components/GitHub_subscriptions.mli
bot-components/GitHub_types.mli
src/actions.ml
src/actions.mli
src/bot.ml
src/github_installations.ml
src/github_installations.mli

Partially implements #278 (~~without removing the project V1 support, so that we can test this while keeping the other one for now~~). What is missing:
@proux01 @silene I intend to test-deploy this, so https://github.com/orgs/coq/projects/11/views/4 and https://github.com/coq/coq/projects/42 should in principle be updated concurrently when new PRs are merged or backported in the 8.20+rc1 milestone.
Close coq/coq#19156.
Close #278.
Close #303.

Migrate release management to GitHub projects v2

---

bot-components/GitHub_subscriptions.ml

This will make it easier to add more events in the future.

Report a bit more information on unsupported github events

---

src/actions.ml

This is a small quality of life improvement IMO.  Ideally, we'd link directly to the running job, but that information is not accessible here, currently.

bug-minimizer: link to run-coq-bug-minimizer/actions

---

src/git_utils.ml
src/git_utils.mli

Should fix the issue at https://github.com/coq/coq/pull/19680#issuecomment-2408603227

Don't leak the token in the error message

---

release.Dockerfile

It seems to require about 70 seconds, let's give it 5 minutes in case it gets even slower in the future.

Longer timeout for depext

---

src/git_utils.ml
src/helpers.ml
src/helpers.mli

On top of #317
Fixes #318
<strike>Except I think it doesn't quite work in the current form</strike>

Include stderr in error reports for easier debugging

---

bot-components.opam
coq-bot.opam
dune-project
release.Dockerfile

This is required since the update of mirage-crypto (#314).
The deployment job was failing because it needed OCaml >= 4.13.
Test deployment in progress: https://github.com/Zimmi48/bot/actions/runs/11554799903

Bump OCaml version used in Docker image.

---

coqbot-config.toml
src/actions.ml
src/actions.mli
src/bot.ml

This is based on the assumption that:
- the GitHub organization is renamed from coq to rocq-prover
- the GitHub repo is renamed at the same time from coq to rocq
- the Inria GitLab repo is renamed at the same time from coq to rocq
- but the Inria GitLab organization is not renamed yet.
This is also postponing the renaming of the bot itself.

Minimal updates for the rocq-prover GitHub organization migration.
